/**
 * Regenerates src/client/api-schema.ts from the Cairn API contract.
 *
 *   npm run api:types                                      # from contract/openapi.json
 *   npm run api:types -- ../cairn-core/api/openapi.json    # copy a newer contract in first
 *
 * contract/openapi.json is a copy of cairnguide/cairn-core api/openapi.json, kept here so the
 * types, the mock API in tests/e2e, and code review all see the same contract.
 * openapi-typescript runs through npx with a pinned version (its peer range doesn't
 * include this project's TypeScript, so it isn't a dev dependency). Fields with a default stay
 * optional, because the client may leave them out of a request.
 */
import { execFileSync } from 'node:child_process';
import { copyFileSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const target = resolve('contract/openapi.json');
const output = resolve('src/client/api-schema.ts');
const source = process.argv[2];
if (source) copyFileSync(resolve(source), target);

execFileSync(
  'npx',
  ['--yes', 'openapi-typescript@7.13.0', target, '-o', output, '--default-non-nullable', 'false'],
  {
    stdio: 'inherit',
  },
);
const header =
  '/* eslint-disable */\n' +
  '// Generated by `npm run api:types` from contract/openapi.json (cairnguide/cairn-core api/openapi.json).\n' +
  '// Do not edit by hand.\n\n';
writeFileSync(output, header + readFileSync(output, 'utf8'));
